import styles from "@/styles/Header.module.css";
import Head from "next/head";
import Header from "./Header";
import { ReactNode } from "react";

const Layout = ({ children }: { children: ReactNode }) => {
    return (
        <>
            <Head>
                <title>Inedis</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=devis-width, initial-scale=1" />
                <link rel="stylesheet" href="/favicon" />
            </Head>
            <Header />
            <main className="main content">{children}</main>
        </>
    );
};

export default Layout;